Repository fashion24-developer/fashion24-back, pull requests merged in 2024-09, with the labels that each got.

#30 🛠️ modify(#29): fancy, fancy_stock 스키마 수정
  prisma/migrations/20240902045114_modify_fancy_and_fancy_stock_option/migration.sql
  prisma/schema.prisma
Labels: 🛠️ Modify

#31 ⚙️ setting(#25): look 테이블에 iamge 칼럼 추가
  prisma/migrations/20240903024815_add_look_image_column/migration.sql
  prisma/schema.prisma
Labels: ⚙ Setting, 🛠️ Modify

#33 📃 doc(#32): auth 컨트롤러 swagger 문서 작업
  src/api/auth/controllers/auth.controller.ts
  src/api/auth/controllers/auth.swagger.ts
  src/bootstrap.service.ts
  src/common/pipes/exists.pipe.ts
Labels: 📃 Doc

#36 Api/#35/fancy create
  package-lock.json
  package.json
  src/api/api.module.ts
  src/api/auth/controllers/auth.controller.ts
  src/api/auth/dtos/token-payload.dto.ts
  src/api/auth/jwt/jwt-auth.guard.ts
  src/api/auth/services/auth.service.ts
  src/api/auth/services/i-auth-service.interface.ts
  src/api/fancy/controllers/fancy.admin.controller.ts
  src/api/fancy/controllers/fancy.swagger.ts
  src/api/fancy/dtos/create-fancy.dto.ts
  src/api/fancy/dtos/fancy.dto.ts
  src/api/fancy/fancy.module.ts
  src/api/fancy/repositories/fancy.repository.ts
  src/api/fancy/repositories/i-fancy-repository.interface.ts
  src/api/fancy/services/fancy.service.ts
  src/api/fancy/services/i-fancy-service.interface.ts
  src/common/interfaces/i-service.interface.ts
Labels: 📬 API

#38 doc(#37): fancy create api 에러 케이스 문서 추가
  src/api/fancy/controllers/fancy.swagger.ts
Labels: 📃 Doc

#44 🛠️ modify(#43): jwt strategy에서 accessToken 쿠키에서 가져오기
  src/api/auth/jwt/jwt.strategy.ts
Labels: 🛠️ Modify

#39 Feat/#14/set winston logger
  package-lock.json
  package.json
  src/bootstrap.service.ts
  src/core/core.module.ts
  src/main.ts
  src/middlewares/logger.middleware.ts
Labels: ⚙ Setting

#47 Feat/#40/fancy pagination
  prisma/migrations/20240911064850_add_suboption_additional_price/migration.sql
  prisma/migrations/20240911081012_delete_fancy_sub_option_option_id/migration.sql
  prisma/migrations/20240911082609_add_unique_in_fancy_sub_option_fancy_option/migration.sql
  prisma/schema.prisma
  src/api/auth/auth.module.ts
  src/api/auth/controllers/auth.controller.ts
  src/api/auth/services/auth.service.ts
  src/api/fancy/constants/fancy-find-all-select.const.ts
  src/api/fancy/controllers/fancy.admin.controller.ts
  src/api/fancy/controllers/fancy.controller.ts
  src/api/fancy/controllers/fancy.swagger.ts
  src/api/fancy/decorators/value-to-number-array.decorator.ts
  src/api/fancy/dtos/create-fancy-input.dto.ts
  src/api/fancy/dtos/create-fancy.dto.ts
  src/api/fancy/dtos/find-all-fancy.dto.ts
  src/api/fancy/enums/fancy-orderby.enum.ts
  src/api/fancy/fancy.module.ts
  src/api/fancy/repositories/fancy.repository.ts
  src/api/fancy/repositories/i-fancy-repository.interface.ts
  src/api/fancy/services/fancy.service.ts
  src/api/fancy/services/i-fancy-service.interface.ts
  src/api/users/controllers/users.controller.ts
  src/api/users/dtos/user-info.dto.ts
  src/api/users/repositories/users.repository.ts
  src/api/users/services/users.service.ts
  src/api/users/users.module.ts
  src/common/constants/di.tokens.ts
  src/common/dtos/pagination/pagination-response.dto.ts
  src/common/dtos/pagination/pagination.dto.ts
  src/common/interfaces/i-repository.interface.ts
  src/common/interfaces/i-service.interface.ts
  src/common/interfaces/pagination/i-pagination-meta.interface.ts
Labels: 📬 API

#48 Api/#45/oauth logout
  src/api/auth/auth-provider-config.ts
  src/api/auth/controllers/auth.controller.ts
  src/api/auth/controllers/auth.swagger.ts
  src/api/auth/jwt/jwt-auth.guard.ts
  src/api/auth/jwt/jwt.strategy.ts
  src/api/auth/repositories/i-token-repository.interface.ts
  src/api/auth/repositories/token.repository.ts
  src/api/auth/services/auth.service.ts
  src/api/auth/services/i-auth-service.interface.ts
  src/api/auth/services/i-token-service.interface.ts
  src/api/auth/services/token.service.ts
  src/api/fancy/dtos/fancy.dto.ts
  src/api/users/dtos/auth.dto.ts
  src/common/dtos/response.dto.ts
  src/common/pipes/exists.pipe.ts
  src/configs/app.route.ts
Labels: 📃 Doc, 📬 API

#53 ✏️ modify(#52): jwt auth guard에서 토큰 header에서 받을 수 있도록 수정
  src/api/auth/jwt/jwt-auth.guard.ts
  src/api/auth/jwt/jwt.strategy.ts
  src/api/auth/repositories/token.repository.ts
Labels: 🛠️ Modify

#55 ✏️ modify(#46): env validation 수정
  src/core/app-config/app-config.module.ts
  src/core/app-config/constants/app-config.constant.ts
Labels: ⚙ Setting

#62 Api/#61/get look
  src/api/api.module.ts
  src/api/fancy/controllers/fancy.controller.ts
  src/api/looks/controllers/look.controller.ts
  src/api/looks/controllers/look.swagger.ts
  src/api/looks/dtos/look-response.dto.ts
  src/api/looks/dtos/look.dto.ts
  src/api/looks/entity/look.entity.ts
  src/api/looks/look.module.ts
  src/api/looks/respositories/i-look-repository.interface.ts
  src/api/looks/respositories/look.repository.ts
  src/api/looks/services/look.service.ts
  src/common/constants/di.tokens.ts
  src/configs/app.route.ts
Labels: 📬 API

#69 Modify/#67/fancy pagination
  prisma/migrations/20240923104925_add_updated_at_default_value/migration.sql
  prisma/schema.prisma
  src/api/apps/fancy/constants/fancy-find-all-select.const.ts
  src/api/apps/fancy/controllers/fancy.app.controller.ts
  src/api/apps/fancy/controllers/fancy.app.swagger.ts
  src/api/apps/fancy/dtos/fancy-pagination-response.dto.ts
  src/api/apps/fancy/dtos/find-all-fancy-response.dto.ts
  src/api/apps/fancy/services/fancy.app.service.ts
  src/common/dtos/pagination/pagination-response.dto.ts
  src/libs/fancy/fancy-images/dtos/fancy-image.dto.ts
  src/libs/fancy/fancy-options/entities/fancy-option.entity.ts
  src/libs/looks/dtos/look.dto.ts
  src/libs/options/entities/option.entity.ts
  src/libs/sub-options/entities/sub-option.entity.ts
  src/libs/tags/dtos/tag.dto.ts
Labels: 🛠️ Modify, 📬 API
