Repository fashion24-developer/fashion24-back, pull requests merged in 2024-10, with the labels that each got.

#72 Setting/#70/modify table
  prisma/migrations/20240801013955_set_schema/migration.sql
  prisma/migrations/20240802073212_set_schema2/migration.sql
  prisma/migrations/20240802075956_set_schema3/migration.sql
  prisma/migrations/20240816070902_add_uniqueid_column/migration.sql
  prisma/migrations/20240816080344_phone/migration.sql
  prisma/migrations/20240816081616_user_provider_enum_edit/migration.sql
  prisma/migrations/20240820080215_add_user_uniqueid_map_name/migration.sql
  prisma/migrations/20240821071039_add_user_token_schema/migration.sql
  prisma/migrations/20240821071914_modify_one_to_one/migration.sql
  prisma/migrations/20240821083935_modify_on_delete/migration.sql
  prisma/migrations/20240830080410_del_user_name_column/migration.sql
  prisma/migrations/20240902045114_modify_fancy_and_fancy_stock_option/migration.sql
  prisma/migrations/20240903024815_add_look_image_column/migration.sql
  prisma/migrations/20240911064850_add_suboption_additional_price/migration.sql
  prisma/migrations/20240911081012_delete_fancy_sub_option_option_id/migration.sql
  prisma/migrations/20240911082609_add_unique_in_fancy_sub_option_fancy_option/migration.sql
  prisma/migrations/20240923104925_add_updated_at_default_value/migration.sql
  prisma/migrations/20241009115515_init/migration.sql
  prisma/schema.prisma
Labels: ⚙ Setting

#76 🐞 bugfix(#75): 소셜 토큰 저장할때 upsert 메서드 사용 (로우 있으면 수정, 없으면 추가)
  src/api/apps/auth/repositories/token.repository.ts
Labels: 🐞 BugFix

#81 🔥 delete(#79): prisma model 변경에 따른 관련 걸림돌 코드 전부 삭제
  src/libs/fancy/repositories/fancy.repository.ts
  src/libs/looks/repositories/look.repository.ts
Labels: ⚙ Setting, ❌ Delete

#80 500번 에러 발생 시 슬랙 메세지 전송 기능 추가
  package-lock.json
  package.json
  src/api/apps/auth/auth-provider-config.ts
  src/api/apps/auth/jwt/jwt.strategy.ts
  src/api/apps/auth/services/token.service.ts
  src/app.module.ts
  src/bootstrap.service.ts
  src/common/interceptors/cookie.interceptor.ts
  src/common/redis/factories/cache-module-options.factory.ts
  src/core/core.module.ts
  src/exceptions/exception-filters.module.ts
  src/exceptions/exception-filters/http-exception.filter.ts
  src/libs/core/app-config/app-config.module.ts
  src/libs/core/app-config/constants/app-config.constant.ts
  src/libs/core/app-config/services/app-config.service.ts
  src/libs/core/app-config/services/i-app-config-service.interface.ts
  src/libs/core/app-config/tokens/app-config.di-token.ts
  src/libs/core/app-config/types/app-config.type.ts
  src/libs/core/core.module.ts
  src/libs/core/messenger/messenger.module.ts
  src/libs/core/messenger/services/i-messenger-service.interface.ts
  src/libs/core/messenger/services/messenger.service.ts
  src/libs/core/messenger/tokens/messenger-service.di-token.ts
  src/libs/core/messenger/types/app-slack.type.ts
  src/libs/exceptions/exception-filters.module.ts
  src/libs/exceptions/exception-filters/http-exception.filter.ts
  src/libs/exceptions/exception-filters/process-error-exception.filter.ts
Labels: ✨ Feat, 🔨 Refactor

#85 Modify/#78/get social user info
  prisma/migrations/20241011081321_add_user_gender_enum/migration.sql
  prisma/migrations/20241011094310_modify_birth_column_type/migration.sql
  prisma/migrations/20241014112131_modify_user_social_refresh_token_to_nullable/migration.sql
  prisma/schema.prisma
  src/api/apps/auth/auth-provider-config.ts
  src/api/apps/users/dtos/create-user.dto.ts
  src/api/apps/users/dtos/social-user-info.dto.ts
  src/api/apps/users/dtos/user-info.dto.ts
  src/api/apps/users/entities/user.entity.ts
  src/api/apps/users/enums/user-gender.enum.ts
  src/api/apps/users/repositories/users.repository.ts
Labels: 🛠️ Modify

#74 🐞 bugfix(#73): CD 로직에서 컨테이너 삭제 후 이미지가 삭제되도록 수정
  .github/workflows/develop-cd.yml
Labels: 🌏 Deploy, 🐞 BugFix
